// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: chunkserver.proto

package chunkserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HeartBeatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HeartBeatMessage) Reset() {
	*x = HeartBeatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunkserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatMessage) ProtoMessage() {}

func (x *HeartBeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatMessage.ProtoReflect.Descriptor instead.
func (*HeartBeatMessage) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HeartBeatMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HeartBeatMessageReply) Reset() {
	*x = HeartBeatMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunkserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatMessageReply) ProtoMessage() {}

func (x *HeartBeatMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatMessageReply.ProtoReflect.Descriptor instead.
func (*HeartBeatMessageReply) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeatMessageReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chunkserver_proto protoreflect.FileDescriptor

var file_chunkserver_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xac, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x67, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x66, 0x73, 0x2f, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chunkserver_proto_rawDescOnce sync.Once
	file_chunkserver_proto_rawDescData = file_chunkserver_proto_rawDesc
)

func file_chunkserver_proto_rawDescGZIP() []byte {
	file_chunkserver_proto_rawDescOnce.Do(func() {
		file_chunkserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_chunkserver_proto_rawDescData)
	})
	return file_chunkserver_proto_rawDescData
}

var file_chunkserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chunkserver_proto_goTypes = []interface{}{
	(*HeartBeatMessage)(nil),      // 0: master.HeartBeatMessage
	(*HeartBeatMessageReply)(nil), // 1: master.HeartBeatMessageReply
}
var file_chunkserver_proto_depIdxs = []int32{
	0, // 0: master.ChunkServer.SendHeartBeatMessage:input_type -> master.HeartBeatMessage
	0, // 1: master.ChunkServer.SayHelloAgain:input_type -> master.HeartBeatMessage
	1, // 2: master.ChunkServer.SendHeartBeatMessage:output_type -> master.HeartBeatMessageReply
	1, // 3: master.ChunkServer.SayHelloAgain:output_type -> master.HeartBeatMessageReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chunkserver_proto_init() }
func file_chunkserver_proto_init() {
	if File_chunkserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chunkserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chunkserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chunkserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunkserver_proto_goTypes,
		DependencyIndexes: file_chunkserver_proto_depIdxs,
		MessageInfos:      file_chunkserver_proto_msgTypes,
	}.Build()
	File_chunkserver_proto = out.File
	file_chunkserver_proto_rawDesc = nil
	file_chunkserver_proto_goTypes = nil
	file_chunkserver_proto_depIdxs = nil
}
