// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: master.proto

package master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	// Sends a heart beat message
	SendHeartBeatMessage(ctx context.Context, in *HeartBeatMessage, opts ...grpc.CallOption) (*HeartBeatMessageReply, error)
	// Sends another greeting
	SayHelloAgain(ctx context.Context, in *HeartBeatMessage, opts ...grpc.CallOption) (*HeartBeatMessageReply, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) SendHeartBeatMessage(ctx context.Context, in *HeartBeatMessage, opts ...grpc.CallOption) (*HeartBeatMessageReply, error) {
	out := new(HeartBeatMessageReply)
	err := c.cc.Invoke(ctx, "/master.Master/SendHeartBeatMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SayHelloAgain(ctx context.Context, in *HeartBeatMessage, opts ...grpc.CallOption) (*HeartBeatMessageReply, error) {
	out := new(HeartBeatMessageReply)
	err := c.cc.Invoke(ctx, "/master.Master/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility
type MasterServer interface {
	// Sends a heart beat message
	SendHeartBeatMessage(context.Context, *HeartBeatMessage) (*HeartBeatMessageReply, error)
	// Sends another greeting
	SayHelloAgain(context.Context, *HeartBeatMessage) (*HeartBeatMessageReply, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (UnimplementedMasterServer) SendHeartBeatMessage(context.Context, *HeartBeatMessage) (*HeartBeatMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartBeatMessage not implemented")
}
func (UnimplementedMasterServer) SayHelloAgain(context.Context, *HeartBeatMessage) (*HeartBeatMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	s.RegisterService(&Master_ServiceDesc, srv)
}

func _Master_SendHeartBeatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SendHeartBeatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SendHeartBeatMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SendHeartBeatMessage(ctx, req.(*HeartBeatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SayHelloAgain(ctx, req.(*HeartBeatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Master_ServiceDesc is the grpc.ServiceDesc for Master service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Master_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartBeatMessage",
			Handler:    _Master_SendHeartBeatMessage_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Master_SayHelloAgain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
